#!/usr/bin/env bash
# Copy Mosquitto ca.crt into nrf9151-firmware mqtt_ca_cert.h (sec tag 43).
#
# Usage (from GPS-Tracking-Server repo root):
#   ./mosquitto/scripts/sync_firmware_mqtt_ca.sh
#   ./mosquitto/scripts/sync_firmware_mqtt_ca.sh /path/to/GPS-Tracking-PCB
#
# Run after generate_certs.sh / ensure_certs.sh, then rebuild and flash firmware.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
CA_CRT="${REPO_ROOT}/mosquitto/config/certs/ca.crt"
PCB_ROOT="${1:-${GPS_TRACKING_PCB:-$(cd "${REPO_ROOT}/../../projects/GPS-Tracking-PCB" 2>/dev/null && pwd || true)}}"

if [[ ! -s "${CA_CRT}" ]]; then
  echo "Missing ${CA_CRT} — run ./mosquitto/scripts/ensure_certs.sh first" >&2
  exit 1
fi

if [[ -z "${PCB_ROOT}" || ! -d "${PCB_ROOT}/nrf9151-firmware" ]]; then
  echo "GPS-Tracking-PCB not found. Pass path as first argument." >&2
  exit 1
fi

OUT="${PCB_ROOT}/nrf9151-firmware/src/drivers/mqtt_ca_cert.h"

python3 - "${CA_CRT}" "${OUT}" <<'PY'
import sys
from pathlib import Path

ca_path, out_path = Path(sys.argv[1]), Path(sys.argv[2])
pem = ca_path.read_text(encoding="utf-8").strip()
if "BEGIN CERTIFICATE" not in pem:
    raise SystemExit(f"Not a PEM certificate: {ca_path}")

lines = []
split = pem.splitlines()
for i, line in enumerate(split):
    suffix = " \\" if i < len(split) - 1 else ""
    lines.append(f'"{line}\\n"{suffix}')

body = "\n".join(lines)

header = f'''/**
 * @file mqtt_ca_cert.h
 * @brief TLS trust anchor for Mosquitto MQTT (port 8883).
 *
 * AUTO-GENERATED by GPS-Tracking-Server/mosquitto/scripts/sync_firmware_mqtt_ca.sh
 * Source: mosquitto/config/certs/ca.crt
 *
 * HTTPS uses SERVER_TLS_SEC_TAG (42, Amazon Root CA). MQTT uses sec tag 43.
 */

#ifndef MQTT_CA_CERT_H
#define MQTT_CA_CERT_H

#define MQTT_TLS_SEC_TAG 43

#define MQTT_CA_CERT_PEM \\
{body}

#endif /* MQTT_CA_CERT_H */
'''

out_path.write_text(header, encoding="utf-8", newline="\n")
print(f"Wrote {out_path}")
PY

echo "Next: rebuild firmware (west build) and flash merged.hex"
